# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Backend
    # =======
    - package-ecosystem: pip
      directory: /backend/
      schedule:
          interval: daily
      open-pull-requests-limit: 100
    # Backend (tailwind)
    - package-ecosystem: npm
      directory: /backend/django_core/tailwind_src/static_src/
      schedule:
          interval: daily
      open-pull-requests-limit: 100

    # Android
    # =======
    - package-ecosystem: npm
      directory: /android/AnimeCore/
      schedule:
          interval: daily
      open-pull-requests-limit: 100

    # Frontend
    # =========
    - package-ecosystem: npm
      directory: /frontend/AnimeCore/
      schedule:
          interval: daily
      open-pull-requests-limit: 100

    - package-ecosystem: npm
      directory: /frontend/User/
      schedule:
          interval: daily
      open-pull-requests-limit: 100

    # Tools
    # Seeder
    # =======
    - package-ecosystem: pip
      directory: /tools/seeder/
      schedule:
          interval: daily
      open-pull-requests-limit: 100

    # Bots
    # =====
    - package-ecosystem: pip
      directory: /bots/discord/
      schedule:
          interval: daily
      open-pull-requests-limit: 100
    # BETA REPOS
    - package-ecosystem: npm
      directory: /frontend/AnimeCore-v2/
      schedule:
          interval: daily
      open-pull-requests-limit: 100
