# Generated by Django 4.1.5 on 2023-01-03 14:48

import apps.torrent_tracker.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import functools
import picklefield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Peer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peer_id", models.CharField(max_length=20, unique=True)),
                ("peer_ip", models.GenericIPAddressField()),
                ("peer_port", models.IntegerField()),
                ("peer_bytes_left", models.IntegerField()),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="TorrentPasskey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=functools.partial(
                            django.utils.crypto.get_random_string, *(40,), **{}
                        ),
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Torrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metainfo_file",
                    models.FileField(upload_to=apps.torrent_tracker.models.upload_to),
                ),
                ("infohash_sha1_hexdigest", models.CharField(max_length=40, unique=True)),
                ("torrent_size", models.IntegerField()),
                ("torrent_files", picklefield.fields.PickledObjectField(editable=False)),
                (
                    "upload_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("peers", models.ManyToManyField(to="torrent_tracker.peer")),
            ],
        ),
    ]
