[tool.poetry]
name = "seeder"
version = "0.1.0"
description = ""
authors = ["baseplate-admin <61817579+baseplate-admin@users.noreply.github.com>"]
license = "AGPL-v3-only"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
humanize = "^4.6.0"
termcolor = "^2.2.0"
requests-cache = {extras = ["redis"], version = "^0.9.8"}
requests-ratelimiter = "*"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
poethepoet = "^0.18.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[tool.poe.tasks]
seed_character = 'python character.py'
seed_staff = 'python staff.py'
